### ISSUE TITLE
Failed to flush metrics: Message size too large: {number} is greater than available size {number}

### ISSUE THREAD

**Issue by sairamch04** [uber-java/tally#65] opened 2020-04-13 08:50 UTC
We've being seeing this exception in our service. This seems to be introduced in this [change](https://github.com/uber-java/tally/pull/59/files#diff-0ab29d028dfc2be47a19838ce2522eb0R90),

This change set `M3Reporter.DEFAULT_MAX_PACKET_SIZE` and `TUdpTransport . UDP_DATA_PAYLOAD_MAX_SIZE` same. Looks like due to transport level headers, the writeBuffer in udpTransport seem to exceed `TUdpTransport.UDP_DATA_PAYLOAD_MAX_SIZE`, resulting in entering [ this exception path](https://github.com/uber-java/tally/pull/59/files#diff-28dcbe79e587ac78ba4e03a8c88bca51R114)

**Comment by sairamch04** [comment] 2020-04-13 08:52
cc: @justinjc @alexeykudinkin

**Comment by alexeykudinkin** [comment] 2020-04-13 16:04
This is caused by an inherent issue, that got triggered after #59 got merged.

Is addressed in #64

**Closed** 2021-08-13 21:17 UTC
